#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinAndroidSandbox.Resource", IsApplication=true)]

namespace XamarinAndroidSandbox
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int uiCompass = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int uiRotateGestures = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int uiScrollGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiTiltGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiZoomControls = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int useViewLifecycle = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int zOrderOnTop = 2130771981;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fail = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int mark_blue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int mark_red = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monkey = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int polarbear = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int success = 2130837510;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int MapWithOverlayButton = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int Name = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Places = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int PlacesSearchButton = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int hybrid = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int mapWithOverlay = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int none = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int normal = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int satellite = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int terrain = 2130968579;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MapWithOverlayLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PlaceListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Places = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050011
			public const int ApplicationName = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int MapWithOverlayText = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int PlacesSearchText = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int activity_label_mapwithmarkers = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int auth_client_availability_notification_title = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int auth_client_play_services_err_notification_msg = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int auth_client_requested_by_msg = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_enable_button = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_enable_text = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_enable_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_install_text_phone = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_install_text_tablet = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_install_title = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_unknown_issue = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_unsupported_text = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_unsupported_title = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_update_button = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_text = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_update_title = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int common_signin_button_text_long = 2131034125;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
